version: "3"
services:
    qbittorrent:
        container_name: qbittorrent
        
        image: lscr.io/linuxserver/qbittorrent
        restart: unless-stopped
        
        volumes:
            - /home/qbittorrent/config:/config
            - /home/qbittorrent/downloads:/downloads
        
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - WEBUI_PORT=8080

        ports:
            - '6881:6881'
            - '6881:6881/udp'
            - '8080:8080'
